### ISSUE TITLE
Cri-Containerd and IPv6

### ISSUE THREAD

**Issue by valentin2105** [containerd/cri-containerd#580] opened 2018-02-01 03:35 UTC
Hi,

I have tried to deploy a IPv6-only cluster using cri-containerd, but I was not able to make it work,

It work at glances using Docker but I really would like to migrate that to cri-containerd.

Here is the log that get droped : 

```
 failed to get IP addresses for \"eth0\": <nil>"
```

I have no more investigations to find what happend ... 
Any idea ?

**Comment by Random-Liu** [comment] 2018-02-01 09:02
@valentin2105 What CNI network plugin are you using? Actually cri-containerd only creates the network namespace. And actual network setting is handled by cni plugins.

**Comment by Random-Liu** [comment] 2018-02-01 09:08
I see. The issue is in ocicni. https://github.com/cri-o/ocicni/blob/master/pkg/ocicni/ocicni.go#L345

It only tries to get `-4` ipv4 address.
However, cni in Kubernetes also tries `-6` https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/network/plugins.go#L290.

**Comment by Random-Liu** [comment] 2018-02-01 09:17
@valentin2105 I sent out a fix in https://github.com/cri-o/ocicni/pull/16. And will update vendor after it is merged.

**Comment by valentin2105** [comment] 2018-02-01 09:41
@Random-Liu  I use Calico as CNI provider who work well using Docker.
I have tried the latest release of cri-containerd (`cri-containerd v1.0.0-beta.1 release`)
Thanks for your work, really looking forward put these dope in production ! 

As I understanded Cri-o doesn't support IPv6 too ? (because you send the link from cri-o) 

Thanks !

**Comment by Random-Liu** [comment] 2018-02-01 09:52
> As I understanded Cri-o doesn't support IPv6 too ? (because you send the link from cri-o)

@valentin2105 We all use that package. And yeah, I think so.

**Closed** 2018-02-02 20:30 UTC
Labels: kind/bug

**Comment by valentin2105** [comment] 2018-02-03 02:22
Thanks for your support, I will try that soon ;)

**Comment by Random-Liu** [comment] 2018-02-03 02:29
@valentin2105 BTW, we disabled the IPv6 DAD by default because it slows down pod creation a lot. You may want to enable it if you need it `--enable-ipv6-dad`.

**Comment by valentin2105** [comment] 2018-02-03 02:30
Great !!
